name: a|r|n|e
markdown: rdiscount
rdiscount:
  extensions:
      - autolink      # greedily urlify links
      - footnotes     # footnotes
      - smart         # typographic substitutions with SmartyPants
pygments: true
baseurl: /_site/
pagination: 5
